### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by yahmad3495** [RyanRongY/cse15l-lab-reports#2]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
- [x] Link to test file for bug/input 1
       -Please include the link to the test file showing the source .md file (github link should fine)
- [x] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [x] Commit screenshot for bug/input 2
- [x] Link to test file for bug/input 2
      -Include the github link to this test file on your repository
- [x] Symptom shown as command + output for bug/input 2
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [x] Commit screenshot for bug/input 3
- [x] Link to test file for bug/input 3
    -Include the github link to this test file on your repository showing the source .md files
- [x] Symptom shown as command + output for bug/input 3
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
Great job! Leave any questions you have about the feedback below!

Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by RyanRongY** [comment]
I did have the link for my testfile for the first time grading, I'm not sure what I am missing. May I ask why I did not get the checkmark for Link to test file for bug/input 1

**Comment by yahmad3495** [comment]
Hello, the link to the test-file should lead to the source code of the markdown file as opposed to the html. You can change the link to the url of the file in your repository.
